/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 earth__terra_-_downloadable_model.glb
Author: murilo.kleine (https://sketchfab.com/murilo.kleine)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-terra-downloadable-model-30fd7e9c4e6946ddb6fcae7a97b2b0d4
Title: Earth | Terra - Downloadable model
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect } from "react";

export default function Model1(props) {
    const { nodes, materials, animations } = useGLTF(
        "/earth.glb"
    );
    const modelRef = useRef(null);
    const previousMouse = useRef({ x: 0, y: 0 });

    useEffect(() => {
        function handleMouseMove(event) {
            const currentMouse = { x: event.clientX, y: event.clientY };
            const deltaMouse = {
                x: currentMouse.x - previousMouse.current.x,
                y: currentMouse.y - previousMouse.current.y,
            };

            modelRef.current.position.x += deltaMouse.x * 0.0005;
            modelRef.current.position.y -= deltaMouse.y * 0.0005;

            previousMouse.current = currentMouse;
        }

        window.addEventListener("mousemove", handleMouseMove);
        return () => {
            window.removeEventListener("mousemove", handleMouseMove);
        };
    }, []);
    // const { actions } = useAnimations(animations, group);
    return (
        <group ref={modelRef} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Root">
                        <group name="EARTH">
                            <mesh
                                name="EARTH_0"
                                geometry={nodes.EARTH_0.geometry}
                                material={materials["Material.001"]}
                            />
                        </group>
                        <group name="Armature">
                            <primitive object={nodes.Armature_rootJoint} />
                            <group name="ATM" scale={1.01} />
                            <skinnedMesh
                                name="ATM_0"
                                geometry={nodes.ATM_0.geometry}
                                material={materials["Material.002"]}
                                skeleton={nodes.ATM_0.skeleton}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/earth.glb");
